on:
  pull_request:
    types: [opened, reopened]
name: Slack Notification Demo
jobs:
  slackNotification:
    if:  startsWith(github.head_ref, 'dependabot/')
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
