on:
  pull_request:
    types: [opened, reopened]
name: Slack Notification Demo
jobs:
  slackNotification:
    if:  startsWith(github.head_ref, 'dependabot/')
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: kceb/pull-request-url-action@v1
      id: pr-url
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: "dependable bot"
        SLACK_MESSAGE: "<${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>"
        SLACK_FOOTER: ""
        SLACK_TITLE: "Dependabot created a PR"
        MSG_MINIMAL: true
